spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
server:
  servlet:
    context-path: /api/v1
jwt:
  secret: SDF345r#$RTGrewageraGRr@Qt$2GhgAWGQFwg@34ythgE
